[package]
name = "devkit-fuzz"
version = "0.0.0"
publish = false
edition = "2021"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
devkit-xdr = { path = "../crates/devkit-xdr" }

[[bin]]
name = "decode_scval"
path = "fuzz_targets/decode_scval.rs"
test = false
doc = false
bench = false

[[bin]]
name = "decode_envelope"
path = "fuzz_targets/decode_envelope.rs"
test = false
doc = false
bench = false

[[bin]]
name = "decode_event"
path = "fuzz_targets/decode_event.rs"
test = false
doc = false
bench = false

[workspace]
